---
id: Pear
name: Pear
full: PEAR infrastructure library
description: >-
  A library that provides various tools to deal with PEAR. Among other features
  it allows updating the package.xml file or accessing a remote PEAR server.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Pear
authors:
  -
    name: Gunnar Wrobel
    user: wrobel
    email: p@rdus.de
    active: true
    role: lead
version:
  release: 2.0.0alpha4
  api: 2.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/util: ^3
      horde/xml_element: ^3
      horde/yaml: ^3
  optional:
    composer:
      horde/http: ^3
      horde/test: ^3
