---
id: Pear
name: Pear
full: PEAR infrastructure library
description: >
  The component provides various tools to deal with PEAR. Among other features
  it allows updating the package.xml file or accessing a remote PEAR server.
list: dev
type: library
